<?php
namespace Litiano\Sap\IdeHelper;

/**
 * Class IBusinessPartners
 * GUID={9DF321C2-6A1D-446B-AE8A-F7C33987D792}
 *
 * @property string $CardCode In this field, type in the code you have chosen for the customer or supplier: a fifteen-character, alphanumeric code
 * @property int|VT_USERDEFINED $CardType From the field's drop down menu you must determine whether  the card is for a customer or supplier. If a business is both a customer and supplier, define two cards.
 * @property string $CardName You must enter the full customer/supplier name in this field.
 * @property int $GroupCode In this field, select the association group for the customer or supplier. You can use this association to generate any report from a specific cross-section of cards.
 * @property string $Address An address should be entered in these fields only if 					  the physical address is not the same as the mailing address.					  If there is no entry for Address in a new card the system will 					  copy the data from Mailing Address to these fields.
 * @property string $ZipCode Zip Code for Company address.
 * @property string $MailAddress In the relevant fields, enter the mailing address provided by the customer or supplier. This address appears on marketing and payment documents generated by TM Pro.
 * @property string $MailZipCode Zip Code for mailing Address.
 * @property string $Phone1 Tel 1 number.
 * @property string $Phone2 Tel 2 number.
 * @property string $Fax Fax number.
 * @property string $ContactPerson Contact person name.
 * @property string $Notes This field allows you to type in any text you want about the customer. For example, “Customer entitled to preferred treatment? or conversely, “No checks?
 * @property int $PayTermsGrpCode Payment terms group number.
 * @property float $CreditLimit Maximal credit.
 * @property float $MaxCommitment Maximal debt.
 * @property float $DiscountPercent Overall Discount %.
 * @property int|VT_USERDEFINED $VatLiable The default is Yes. If the customer is exempt, you must select the No option.
 * @property string $FederalTaxID Type the customer or supplier L.T. no. in this field.
 * @property int|VT_USERDEFINED $DeductibleAtSource Choosing YES for Customer Card indicates that the customer must deduct tax from payments that he pays you.
 * @property float $DeductionPercent You must enter the percentage given in the certificate provided by the supplier.A percentage deduction at source of 5% must be typed as 5, and not as 0.05.
 * @property string|VT_DATE $DeductionValidUntil Type in the termination date of the certificate provided by the supplier.
 * @property int $PriceListNum Price list number.
 * @property float $IntrestRatePercent The field specifies the percentage of interest on a delay in payment.  This field is for information only.
 * @property float $CommissionPercent Overwrites the contents of the Percentage Commission field.
 * @property int $CommissionGroupCode Select the desired commission group Number.
 * @property string $FreeText Free text such as remarks or other details about the card.
 * @property int $SalesPersonCode Sales employee code.
 * @property string $Currency The card currency is the currency in which all journal entries and marketing documents for that card are performed. The card’s default currency is the local currency, and it is used for all journal entries.
 * @property string $RateDiffAccount Exchange rate differential account.
 * @property string $Cellular Cellular phone number.
 * @property int $AvarageLate In this field, you can type in the average payments delay in days for a specific customer. Entering a value in this field adjusts the value dates of the customer debts in the Cash Flow report.
 * @property string $City City name for company address.
 * @property string $County County name for company address.
 * @property string $Country Country name for company address.
 * @property string $MailCity City for mailing address.
 * @property string $MailCounty County for mailing address.
 * @property string $MailCountry Country for mailing address.
 * @property string $EmailAddress Company's main Email address.
 * @property string $Picture Picture file name - do not include the full path , only the file name.
 * @property string $DefaultAccount Default bank account.
 * @property string $DefaultBranch Default branch.
 * @property string $DefaultBankCode Default bank code.
 * @property string $AdditionalID This field allows you to type in an additional ID no. for the card.
 * @property string $Pager Pager number.
 * @property string $FatherCard Father card.
 * @property string $CardForeignName A foreign name can be entered (up to 100 characters). This name will be entered into foreign documents (for example, in an invoice sent to a customer abroad).
 * @property int|VT_USERDEFINED $FatherType Father type.
 * @property int|VT_USERDEFINED $Properties You use card characteristics for cross-sections and an additional sort of the customer and supplier cards.
 * @property string $DeductionOffice Enter in this field the name of the authorizing official that appears on the supplier’s deduction certificate.
 * @property string $ExportCode Code for data export
 * @property float $MinIntrest Minimal intrest.
 * @property-read IUserFields $UserFields User fields for this object.
 * @property-read float $CurrentAccountBalance property CurrentAccountBalance
 * @property-read float $OpenDeliveryNotesBalance property OpenDeliveryNotesBalance
 * @property-read float $OpenOrdersBalance property OpenOrdersBalance
 * @property-read mixed|VT_PTR $ContactEmployees property ContactEmployees
 * @property string $VatGroup property VatGroup
 * @property int $ShippingType property ShippingType
 * @property string $Password property Password
 * @property string $Indicator property Indicator
 * @property string $IBAN property IBAN
 * @property int $CreditCardCode property CreditCardCode
 * @property string $CreditCardNum property CreditCardNum
 * @property string|VT_DATE $CreditCardExpiration property CreditCardExpiration
 * @property string $DebitorAccount property PayaybleAccount
 * @property-read int $OpenOpportunities property OpenOpportunities
 * @property int|VT_USERDEFINED $Valid property Valid
 * @property string|VT_DATE $ValidFrom property ValidFrom
 * @property string|VT_DATE $ValidTo property ValidTo
 * @property string $ValidRemarks property ValidRemarks
 * @property int|VT_USERDEFINED $Frozen property Frozen
 * @property string|VT_DATE $FrozenFrom property FrozenFrom
 * @property string|VT_DATE $FrozenTo property FrozenTo
 * @property string $FrozenRemarks property FrozenRemarks
 * @property-read mixed|VT_PTR $Browser User fields for this object.
 * @property-read mixed|VT_PTR $Addresses property Addresses
 * @property string $Block property Block
 * @property string $BillToState property BillToState
 * @property string $ExemptNum property ExemptNum
 * @property int $Priority property Priority
 * @property int $FormCode1099 property FormCode1099
 * @property string $Box1099 property Box1099
 * @property string $PeymentMethodCode property PeymentMethodCode
 * @property int|VT_USERDEFINED $BackOrder property BackOrder
 * @property int|VT_USERDEFINED $PartialDelivery property PartialDelivery
 * @property int|VT_USERDEFINED $BlockDunning property BlockDunning
 * @property string $BankCountry property BankCountry
 * @property string $HouseBank property HouseBank
 * @property string $HouseBankCountry property HouseBankCountry
 * @property string $HouseBankAccount property HouseBankAccount
 * @property string $ShipToDefault property ShipToDefault
 * @property-read int $DunningLevel property DunningLevel
 * @property-read string|VT_DATE $DunningDate property DunningDate
 * @property int|VT_USERDEFINED $CollectionAuthorization property CollectionAuthorization
 * @property string $DME property DME
 * @property string $InstructionKey property InstructionKey
 * @property int|VT_USERDEFINED $SinglePayment property SinglePayment
 * @property string $ISRBillerID property ISRBillerID
 * @property int|VT_USERDEFINED $PaymentBlock property PaymentBlock
 * @property string $ReferenceDetails property ReferenceDetails
 * @property string $HouseBankBranch property HouseBankBranch
 * @property string $OwnerIDNumber property OwnerIDNumber
 * @property int $PaymentBlockDescription property PaymentBlockDescription
 * @property string $TaxExemptionLetterNum property TaxExemptionLetterNum
 * @property float $MaxAmountOfExemption property MaxAmountOfExemption
 * @property string|VT_DATE $ExemptionValidityDateFrom property ExemptionValidityDateFrom
 * @property string|VT_DATE $ExemptionValidityDateTo property ExemptionValidityDateTo
 * @property-read mixed|VT_PTR $AccountRecivablePayables property AccountRecivablePayables
 * @property string $LinkedBusinessPartner property LinkedBusinessPartner
 * @property int $LastMultiReconciliationNum property LastMultiReconciliationNum
 * @property int|VT_USERDEFINED $Equalization property Equalization
 * @property int|VT_USERDEFINED $SubjectToWithholdingTax property SubjectToWithholdingTax
 * @property string $CertificateNumber property CertificateNumber
 * @property string|VT_DATE $ExpirationDate property ExpirationDate
 * @property string $NationalInsuranceNum property NationalInsuranceNum
 * @property int|VT_USERDEFINED $AccrualCriteria property AccrualCriteria
 * @property string $WTCode property WTCode
 * @property int|VT_USERDEFINED $DeferredTax property DeferredTax
 * @property string $BillToBuildingFloorRoom property BillToBuildingFloorRoom
 * @property string $DownPaymentClearAct property DownPaymentClearAct
 * @property string $ChannelBP property ChannelBP
 * @property int $DefaultTechnician property DefaultTechnician
 * @property string $BilltoDefault property BilltoDefault
 * @property string $CustomerBillofExchangDisc property CustomerBillofExchangDisc
 * @property int $Territory property Territory
 * @property string $ShipToBuildingFloorRoom property ShipToBuildingFloorRoom
 * @property string $CustomerBillofExchangPres property CustomerBillofExchangPres
 * @property-read mixed|VT_PTR $BPPaymentMethods property BPPaymentMethods
 * @property-read mixed|VT_PTR $BPWithholdingTax property BPWithholdingTax
 * @property-read mixed|VT_PTR $BPPaymentDates property BPPaymentDates
 * @property-read mixed|VT_PTR $BPBankAccounts property BPBankAccounts
 * @property string $ProjectCode property ProjectCode
 * @property string $VatGroupLatinAmerica property VatGroupLatinAmerica
 * @property string $DunningTerm property DunningTerm
 * @property string $Website property Website
 * @property string $OtherReceivablePayable property OtherReceivablePayable
 * @property int $ClosingDateProcedureNumber property ClosingDateProcedureNumber
 * @property string $Profession property Profession
 * @property string $BillofExchangeonCollection property BillofExchangeonCollection
 * @property int|VT_USERDEFINED $CompanyPrivate property CompanyPrivate
 * @property int $LanguageCode property LanguageCode
 * @property string $UnpaidBillofExchange property UnpaidBillofExchange
 * @property int $WithholdingTaxDeductionGroup property WithholdingTaxDeductionGroup
 * @property string $BankChargesAllocationCode property BankChargesAllocationCode
 * @property-read mixed|VT_PTR $FiscalTaxID property FiscalTaxID
 * @property int|VT_USERDEFINED $TaxRoundingRule property TaxRoundingRule
 * @property string $CompanyRegistrationNumber property CompanyRegistrationNumber
 * @property string $VerificationNumber property VerificationNumber
 * @property int|VT_USERDEFINED $OperationCode347 property OperationCode347
 * @property int|VT_USERDEFINED $InsuranceOperation347 property InsuranceOperation347
 * @property int|VT_USERDEFINED $DiscountBaseObject property DiscountBaseObject
 * @property int|VT_USERDEFINED $DiscountRelations property DiscountRelations
 * @property-read mixed|VT_PTR $DiscountGroups property DiscountGroups
 * @property int|VT_USERDEFINED $TypeReport property TypeReport
 * @property int|VT_USERDEFINED $ThresholdOverlook property ThresholdOverlook
 * @property int|VT_USERDEFINED $SurchargeOverlook property SurchargeOverlook
 * @property string $DownPaymentInterimAccount property DownPaymentInterimAccount
 * @property int|VT_USERDEFINED $HierarchicalDeduction property HierarchicalDeduction
 * @property int|VT_USERDEFINED $ShaamGroup property ShaamGroup
 * @property int|VT_USERDEFINED $WithholdingTaxCertified property WithholdingTaxCertified
 * @property int|VT_USERDEFINED $BookkeepingCertified property BookkeepingCertified
 * @property string $PlanningGroup property PlanningGroup
 * @property int|VT_USERDEFINED $Affiliate property Affiliate
 * @property int $Industry property Industry
 * @property string $VatIDNum property VatIDNum
 * @property int $DatevAccount property DatevAccount
 * @property int|VT_USERDEFINED $DatevFirstDataEntry property DatevFirstDataEntry
 * @property string $GTSRegNo property GTSRegNo
 * @property string $GTSBankAccountNo property GTSBankAccountNo
 * @property string $GTSBillingAddrTel property GTSBillingAddrTel
 * @property int $ETaxWebSite property ETaxWebSite
 * @property-read string $HouseBankIBAN property HouseBankIBAN
 * @property int $Series property Series
 * @property int|VT_USERDEFINED $AutomaticPosting property AutomaticPosting
 * @property string $InterestAccount property InterestAccount
 * @property string $FeeAccount property FeeAccount
 * @property int $CampaignNumber property CampaignNumber
 * @property string $VATRegistrationNumber property VATRegistrationNumber
 * @property string $RepresentativeName property RepresentativeName
 * @property string $IndustryType property IndustryType
 * @property string $BusinessType property BusinessType
 * @property-read mixed|VT_PTR $BPBranchAssignment property BPBranchAssignment
 * @property string $AliasName property AliasName
 * @property int $DefaultBlanketAgreementNumber property DefaultBlanketAgreementNumber
 * @property int|VT_USERDEFINED $EffectiveDiscount property EffectiveDiscount
 * @property int|VT_USERDEFINED $NoDiscounts property NoDiscounts
 * @property string $GlobalLocationNumber property GlobalLocationNumber
 * @property string $EDISenderID property EDISenderID
 * @property string $EDIRecipientID property EDIRecipientID
 * @property int|VT_USERDEFINED $ResidenNumber property ResidenNumber
 * @property-read mixed|VT_PTR $IntrastatExtension property IntrastatExtension
 * @property string $UnifiedFederalTaxID property UnifiedFederalTaxID
 * @property string|VT_DATE $RelationshipDateFrom property RelationshipDateFrom
 * @property string|VT_DATE $RelationshipDateTill property RelationshipDateTill
 * @property string $RelationshipCode property RelationshipCode
 * @property int $AttachmentEntry property AttachmentEntry
 * @property int|VT_USERDEFINED $TypeOfOperation property TypeOfOperation
 * @property int $OwnerCode property OwnerCode
 * @property int|VT_USERDEFINED $EndorsableChecksFromBP property EndorsableChecksFromBP
 * @property int|VT_USERDEFINED $AcceptsEndorsedChecks property AcceptsEndorsedChecks
 * @property int|VT_USERDEFINED $BlockSendingMarketingContent property BlockSendingMarketingContent
 * @property-read mixed|VT_PTR $BPBlockSendingMarketingContents property BPBlockSendingMarketingContents
 * @property string $AgentCode property AgentCode
 */
class IBusinessPartners 
{
	/**
	 * DISPID=1610612736
	 * @param int|VT_USERDEFINED $riid [in]
	 * @param mixed|VT_PTR $ppvObj [out]
	 * @return void 
	 */
	function QueryInterface(
		/* mixed|VT_PTR [26] [in] --> int|VT_USERDEFINED [29]  */ &$riid,
		/* mixed|VT_PTR [26] [out] --> mixed|VT_PTR [26]  */ &$ppvObj 
	)
	{
	}

	/**
	 * DISPID=1610612737
	 * @return string 
	 */
	function AddRef()
	{
	}

	/**
	 * DISPID=1610612738
	 * @return string 
	 */
	function Release()
	{
	}

	/**
	 * DISPID=1610678272
	 * @param int $pctinfo [out]
	 * @return void 
	 */
	function GetTypeInfoCount(
		/* mixed|VT_PTR [26] [out] --> int [23]  */ &$pctinfo 
	)
	{
	}

	/**
	 * DISPID=1610678273
	 * @param int $itinfo [in]
	 * @param string $lcid [in]
	 * @param mixed|VT_PTR $pptinfo [out]
	 * @return void 
	 */
	function GetTypeInfo(
		/* int [23] [in] */ $itinfo,
		/* string [19] [in] */ $lcid,
		/* mixed|VT_PTR [26] [out] --> mixed|VT_PTR [26]  */ &$pptinfo 
	)
	{
	}

	/**
	 * DISPID=1610678274
	 * @param int|VT_USERDEFINED $riid [in]
	 * @param mixed|VT_PTR $rgszNames [in]
	 * @param int $cNames [in]
	 * @param string $lcid [in]
	 * @param int $rgdispid [out]
	 * @return void 
	 */
	function GetIDsOfNames(
		/* mixed|VT_PTR [26] [in] --> int|VT_USERDEFINED [29]  */ &$riid,
		/* mixed|VT_PTR [26] [in] --> mixed|VT_PTR [26]  */ &$rgszNames,
		/* int [23] [in] */ $cNames,
		/* string [19] [in] */ $lcid,
		/* mixed|VT_PTR [26] [out] --> int [3]  */ &$rgdispid 
	)
	{
	}

	/**
	 * DISPID=1610678275
	 * @param int $dispidMember [in]
	 * @param int|VT_USERDEFINED $riid [in]
	 * @param string $lcid [in]
	 * @param string $wFlags [in]
	 * @param int|VT_USERDEFINED $pdispparams [in]
	 * @param variant|VT_VARIANT $pvarResult [out]
	 * @param int|VT_USERDEFINED $pexcepinfo [out]
	 * @param int $puArgErr [out]
	 * @return void 
	 */
	function Invoke(
		/* int [3] [in] */ $dispidMember,
		/* mixed|VT_PTR [26] [in] --> int|VT_USERDEFINED [29]  */ &$riid,
		/* string [19] [in] */ $lcid,
		/* string [18] [in] */ $wFlags,
		/* mixed|VT_PTR [26] [in] --> int|VT_USERDEFINED [29]  */ &$pdispparams,
		/* mixed|VT_PTR [26] [out] --> variant|VT_VARIANT [12]  */ &$pvarResult,
		/* mixed|VT_PTR [26] [out] --> int|VT_USERDEFINED [29]  */ &$pexcepinfo,
		/* mixed|VT_PTR [26] [out] --> int [23]  */ &$puArgErr 
	)
	{
	}

	/**
	 * DISPID=1
	 * @var string $CardCode [8] In this field, type in the code you have chosen for the customer or supplier: a fifteen-character, alphanumeric code
	*/
	var $CardCode;

	/**
	 * DISPID=3
	 * @var int|VT_USERDEFINED $CardType [29] From the field's drop down menu you must determine whether  the card is for a customer or supplier. If a business is both a customer and supplier, define two cards.
	*/
	var $CardType;

	/**
	 * DISPID=4
	 * @var string $CardName [8] You must enter the full customer/supplier name in this field.
	*/
	var $CardName;

	/**
	 * DISPID=5
	 * @var int $GroupCode [3] In this field, select the association group for the customer or supplier. You can use this association to generate any report from a specific cross-section of cards.
	*/
	var $GroupCode;

	/**
	 * DISPID=7
	 * @var string $Address [8] An address should be entered in these fields only if 					  the physical address is not the same as the mailing address.					  If there is no entry for Address in a new card the system will 					  copy the data from Mailing Address to these fields.
	*/
	var $Address;

	/**
	 * DISPID=8
	 * @var string $ZipCode [8] Zip Code for Company address.
	*/
	var $ZipCode;

	/**
	 * DISPID=9
	 * @var string $MailAddress [8] In the relevant fields, enter the mailing address provided by the customer or supplier. This address appears on marketing and payment documents generated by TM Pro.
	*/
	var $MailAddress;

	/**
	 * DISPID=10
	 * @var string $MailZipCode [8] Zip Code for mailing Address.
	*/
	var $MailZipCode;

	/**
	 * DISPID=11
	 * @var string $Phone1 [8] Tel 1 number.
	*/
	var $Phone1;

	/**
	 * DISPID=12
	 * @var string $Phone2 [8] Tel 2 number.
	*/
	var $Phone2;

	/**
	 * DISPID=13
	 * @var string $Fax [8] Fax number.
	*/
	var $Fax;

	/**
	 * DISPID=14
	 * @var string $ContactPerson [8] Contact person name.
	*/
	var $ContactPerson;

	/**
	 * DISPID=15
	 * @var string $Notes [8] This field allows you to type in any text you want about the customer. For example, “Customer entitled to preferred treatment? or conversely, “No checks?
	*/
	var $Notes;

	/**
	 * DISPID=16
	 * @var int $PayTermsGrpCode [3] Payment terms group number.
	*/
	var $PayTermsGrpCode;

	/**
	 * DISPID=17
	 * @var float $CreditLimit [5] Maximal credit.
	*/
	var $CreditLimit;

	/**
	 * DISPID=18
	 * @var float $MaxCommitment [5] Maximal debt.
	*/
	var $MaxCommitment;

	/**
	 * DISPID=19
	 * @var float $DiscountPercent [5] Overall Discount %.
	*/
	var $DiscountPercent;

	/**
	 * DISPID=20
	 * @var int|VT_USERDEFINED $VatLiable [29] The default is Yes. If the customer is exempt, you must select the No option.
	*/
	var $VatLiable;

	/**
	 * DISPID=21
	 * @var string $FederalTaxID [8] Type the customer or supplier L.T. no. in this field.
	*/
	var $FederalTaxID;

	/**
	 * DISPID=22
	 * @var int|VT_USERDEFINED $DeductibleAtSource [29] Choosing YES for Customer Card indicates that the customer must deduct tax from payments that he pays you.
	*/
	var $DeductibleAtSource;

	/**
	 * DISPID=23
	 * @var float $DeductionPercent [5] You must enter the percentage given in the certificate provided by the supplier.A percentage deduction at source of 5% must be typed as 5, and not as 0.05.
	*/
	var $DeductionPercent;

	/**
	 * DISPID=24
	 * @var string|VT_DATE $DeductionValidUntil [7] Type in the termination date of the certificate provided by the supplier.
	*/
	var $DeductionValidUntil;

	/**
	 * DISPID=25
	 * @var int $PriceListNum [3] Price list number.
	*/
	var $PriceListNum;

	/**
	 * DISPID=26
	 * @var float $IntrestRatePercent [5] The field specifies the percentage of interest on a delay in payment.  This field is for information only.
	*/
	var $IntrestRatePercent;

	/**
	 * DISPID=27
	 * @var float $CommissionPercent [5] Overwrites the contents of the Percentage Commission field.
	*/
	var $CommissionPercent;

	/**
	 * DISPID=28
	 * @var int $CommissionGroupCode [3] Select the desired commission group Number.
	*/
	var $CommissionGroupCode;

	/**
	 * DISPID=29
	 * @var string $FreeText [8] Free text such as remarks or other details about the card.
	*/
	var $FreeText;

	/**
	 * DISPID=30
	 * @var int $SalesPersonCode [3] Sales employee code.
	*/
	var $SalesPersonCode;

	/**
	 * DISPID=31
	 * @var string $Currency [8] The card currency is the currency in which all journal entries and marketing documents for that card are performed. The card’s default currency is the local currency, and it is used for all journal entries.
	*/
	var $Currency;

	/**
	 * DISPID=32
	 * @var string $RateDiffAccount [8] Exchange rate differential account.
	*/
	var $RateDiffAccount;

	/**
	 * DISPID=33
	 * @var string $Cellular [8] Cellular phone number.
	*/
	var $Cellular;

	/**
	 * DISPID=34
	 * @var int $AvarageLate [3] In this field, you can type in the average payments delay in days for a specific customer. Entering a value in this field adjusts the value dates of the customer debts in the Cash Flow report.
	*/
	var $AvarageLate;

	/**
	 * DISPID=35
	 * @var string $City [8] City name for company address.
	*/
	var $City;

	/**
	 * DISPID=36
	 * @var string $County [8] County name for company address.
	*/
	var $County;

	/**
	 * DISPID=37
	 * @var string $Country [8] Country name for company address.
	*/
	var $Country;

	/**
	 * DISPID=38
	 * @var string $MailCity [8] City for mailing address.
	*/
	var $MailCity;

	/**
	 * DISPID=39
	 * @var string $MailCounty [8] County for mailing address.
	*/
	var $MailCounty;

	/**
	 * DISPID=40
	 * @var string $MailCountry [8] Country for mailing address.
	*/
	var $MailCountry;

	/**
	 * DISPID=41
	 * @var string $EmailAddress [8] Company's main Email address.
	*/
	var $EmailAddress;

	/**
	 * DISPID=42
	 * @var string $Picture [8] Picture file name - do not include the full path , only the file name.
	*/
	var $Picture;

	/**
	 * DISPID=43
	 * @var string $DefaultAccount [8] Default bank account.
	*/
	var $DefaultAccount;

	/**
	 * DISPID=44
	 * @var string $DefaultBranch [8] Default branch.
	*/
	var $DefaultBranch;

	/**
	 * DISPID=45
	 * @var string $DefaultBankCode [8] Default bank code.
	*/
	var $DefaultBankCode;

	/**
	 * DISPID=46
	 * @var string $AdditionalID [8] This field allows you to type in an additional ID no. for the card.
	*/
	var $AdditionalID;

	/**
	 * DISPID=47
	 * @var string $Pager [8] Pager number.
	*/
	var $Pager;

	/**
	 * DISPID=48
	 * @var string $FatherCard [8] Father card.
	*/
	var $FatherCard;

	/**
	 * DISPID=49
	 * @var string $CardForeignName [8] A foreign name can be entered (up to 100 characters). This name will be entered into foreign documents (for example, in an invoice sent to a customer abroad).
	*/
	var $CardForeignName;

	/**
	 * DISPID=50
	 * @return int 
	 * Use this function to add the card to the system.
	 */
	function Add()
	{
	}

	/**
	 * DISPID=51
	 * @var int|VT_USERDEFINED $FatherType [29] Father type.
	*/
	var $FatherType;

	/**
	 * DISPID=52
	 * @var int|VT_USERDEFINED $Properties [29] You use card characteristics for cross-sections and an additional sort of the customer and supplier cards.
	*/
	var $Properties;

	/**
	 * DISPID=53
	 * @var string $DeductionOffice [8] Enter in this field the name of the authorizing official that appears on the supplier’s deduction certificate.
	*/
	var $DeductionOffice;

	/**
	 * DISPID=54
	 * @var string $ExportCode [8] Code for data export
	*/
	var $ExportCode;

	/**
	 * DISPID=55
	 * @var float $MinIntrest [5] Minimal intrest.
	*/
	var $MinIntrest;

	/**
	 * DISPID=57
	 * @param string $CardCode 
	 * @return bool 
	 * Get a card object by it's key (string value).
	 */
	function GetByKey(
		/* string [8]  */ $CardCode 
	)
	{
	}

	/**
	 * DISPID=58
	 * @var IUserFields $UserFields [26] User fields for this object.
	*/
	var $UserFields;

	/**
	 * DISPID=59
	 * @param string $FileName [in][out]
	 * @return void 
	 * Save the objects data in xml format.
	 */
	function SaveXML(
		/* mixed|VT_PTR [26] [in][out] --> string [8]  */ &$FileName 
	)
	{
	}

	/**
	 * DISPID=60
	 * @return int 
	 * method Update
	 */
	function Update()
	{
	}

	/**
	 * DISPID=61
	 * @var float $CurrentAccountBalance [5] property CurrentAccountBalance
	*/
	var $CurrentAccountBalance;

	/**
	 * DISPID=62
	 * @var float $OpenDeliveryNotesBalance [5] property OpenDeliveryNotesBalance
	*/
	var $OpenDeliveryNotesBalance;

	/**
	 * DISPID=63
	 * @var float $OpenOrdersBalance [5] property OpenOrdersBalance
	*/
	var $OpenOrdersBalance;

	/**
	 * DISPID=64
	 * @var IContactEmployees $ContactEmployees [26] property ContactEmployees
	*/
	var $ContactEmployees;

	/**
	 * DISPID=65
	 * @var string $VatGroup [8] property VatGroup
	*/
	var $VatGroup;

	/**
	 * DISPID=66
	 * @var int $ShippingType [3] property ShippingType
	*/
	var $ShippingType;

	/**
	 * DISPID=67
	 * @var string $Password [8] property Password
	*/
	var $Password;

	/**
	 * DISPID=68
	 * @var string $Indicator [8] property Indicator
	*/
	var $Indicator;

	/**
	 * DISPID=69
	 * @var string $IBAN [8] property IBAN
	*/
	var $IBAN;

	/**
	 * DISPID=70
	 * @var int $CreditCardCode [3] property CreditCardCode
	*/
	var $CreditCardCode;

	/**
	 * DISPID=71
	 * @var string $CreditCardNum [8] property CreditCardNum
	*/
	var $CreditCardNum;

	/**
	 * DISPID=72
	 * @var string|VT_DATE $CreditCardExpiration [7] property CreditCardExpiration
	*/
	var $CreditCardExpiration;

	/**
	 * DISPID=73
	 * @var string $DebitorAccount [8] property PayaybleAccount
	*/
	var $DebitorAccount;

	/**
	 * DISPID=74
	 * @return int 
	 * method Remove
	 */
	function Remove()
	{
	}

	/**
	 * DISPID=75
	 * @return int 
	 * method Cancel
	 */
	function Cancel()
	{
	}

	/**
	 * DISPID=76
	 * @return int 
	 * method Close
	 */
	function Close()
	{
	}

	/**
	 * DISPID=77
	 * @var int $OpenOpportunities [3] property OpenOpportunities
	*/
	var $OpenOpportunities;

	/**
	 * DISPID=78
	 * @var int|VT_USERDEFINED $Valid [29] property Valid
	*/
	var $Valid;

	/**
	 * DISPID=79
	 * @var string|VT_DATE $ValidFrom [7] property ValidFrom
	*/
	var $ValidFrom;

	/**
	 * DISPID=80
	 * @var string|VT_DATE $ValidTo [7] property ValidTo
	*/
	var $ValidTo;

	/**
	 * DISPID=81
	 * @var string $ValidRemarks [8] property ValidRemarks
	*/
	var $ValidRemarks;

	/**
	 * DISPID=82
	 * @var int|VT_USERDEFINED $Frozen [29] property Frozen
	*/
	var $Frozen;

	/**
	 * DISPID=83
	 * @var string|VT_DATE $FrozenFrom [7] property FrozenFrom
	*/
	var $FrozenFrom;

	/**
	 * DISPID=84
	 * @var string|VT_DATE $FrozenTo [7] property FrozenTo
	*/
	var $FrozenTo;

	/**
	 * DISPID=85
	 * @var string $FrozenRemarks [8] property FrozenRemarks
	*/
	var $FrozenRemarks;

	/**
	 * DISPID=86
	 * @var mixed|VT_PTR $Browser [26] User fields for this object.
	*/
	var $Browser;

	/**
	 * DISPID=87
	 * @var IBPAddresses $Addresses [26] property Addresses
	*/
	var $Addresses;

	/**
	 * DISPID=88
	 * @var string $Block [8] property Block
	*/
	var $Block;

	/**
	 * DISPID=89
	 * @var string $BillToState [8] property BillToState
	*/
	var $BillToState;

	/**
	 * DISPID=90
	 * @var string $ExemptNum [8] property ExemptNum
	*/
	var $ExemptNum;

	/**
	 * DISPID=91
	 * @var int $Priority [3] property Priority
	*/
	var $Priority;

	/**
	 * DISPID=92
	 * @var int $FormCode1099 [3] property FormCode1099
	*/
	var $FormCode1099;

	/**
	 * DISPID=93
	 * @var string $Box1099 [8] property Box1099
	*/
	var $Box1099;

	/**
	 * DISPID=94
	 * @var string $PeymentMethodCode [8] property PeymentMethodCode
	*/
	var $PeymentMethodCode;

	/**
	 * DISPID=95
	 * @var int|VT_USERDEFINED $BackOrder [29] property BackOrder
	*/
	var $BackOrder;

	/**
	 * DISPID=96
	 * @var int|VT_USERDEFINED $PartialDelivery [29] property PartialDelivery
	*/
	var $PartialDelivery;

	/**
	 * DISPID=97
	 * @var int|VT_USERDEFINED $BlockDunning [29] property BlockDunning
	*/
	var $BlockDunning;

	/**
	 * DISPID=98
	 * @var string $BankCountry [8] property BankCountry
	*/
	var $BankCountry;

	/**
	 * DISPID=99
	 * @var string $HouseBank [8] property HouseBank
	*/
	var $HouseBank;

	/**
	 * DISPID=100
	 * @var string $HouseBankCountry [8] property HouseBankCountry
	*/
	var $HouseBankCountry;

	/**
	 * DISPID=101
	 * @var string $HouseBankAccount [8] property HouseBankAccount
	*/
	var $HouseBankAccount;

	/**
	 * DISPID=102
	 * @var string $ShipToDefault [8] property ShipToDefault
	*/
	var $ShipToDefault;

	/**
	 * DISPID=103
	 * @var int $DunningLevel [3] property DunningLevel
	*/
	var $DunningLevel;

	/**
	 * DISPID=104
	 * @var string|VT_DATE $DunningDate [7] property DunningDate
	*/
	var $DunningDate;

	/**
	 * DISPID=105
	 * @var int|VT_USERDEFINED $CollectionAuthorization [29] property CollectionAuthorization
	*/
	var $CollectionAuthorization;

	/**
	 * DISPID=106
	 * @var string $DME [8] property DME
	*/
	var $DME;

	/**
	 * DISPID=107
	 * @var string $InstructionKey [8] property InstructionKey
	*/
	var $InstructionKey;

	/**
	 * DISPID=108
	 * @var int|VT_USERDEFINED $SinglePayment [29] property SinglePayment
	*/
	var $SinglePayment;

	/**
	 * DISPID=109
	 * @var string $ISRBillerID [8] property ISRBillerID
	*/
	var $ISRBillerID;

	/**
	 * DISPID=110
	 * @var int|VT_USERDEFINED $PaymentBlock [29] property PaymentBlock
	*/
	var $PaymentBlock;

	/**
	 * DISPID=111
	 * @var string $ReferenceDetails [8] property ReferenceDetails
	*/
	var $ReferenceDetails;

	/**
	 * DISPID=112
	 * @var string $HouseBankBranch [8] property HouseBankBranch
	*/
	var $HouseBankBranch;

	/**
	 * DISPID=113
	 * @var string $OwnerIDNumber [8] property OwnerIDNumber
	*/
	var $OwnerIDNumber;

	/**
	 * DISPID=114
	 * @var int $PaymentBlockDescription [3] property PaymentBlockDescription
	*/
	var $PaymentBlockDescription;

	/**
	 * DISPID=115
	 * @var string $TaxExemptionLetterNum [8] property TaxExemptionLetterNum
	*/
	var $TaxExemptionLetterNum;

	/**
	 * DISPID=116
	 * @var float $MaxAmountOfExemption [5] property MaxAmountOfExemption
	*/
	var $MaxAmountOfExemption;

	/**
	 * DISPID=117
	 * @var string|VT_DATE $ExemptionValidityDateFrom [7] property ExemptionValidityDateFrom
	*/
	var $ExemptionValidityDateFrom;

	/**
	 * DISPID=118
	 * @var string|VT_DATE $ExemptionValidityDateTo [7] property ExemptionValidityDateTo
	*/
	var $ExemptionValidityDateTo;

	/**
	 * DISPID=119
	 * @var mixed|VT_PTR $AccountRecivablePayables [26] property AccountRecivablePayables
	*/
	var $AccountRecivablePayables;

	/**
	 * DISPID=120
	 * @var string $LinkedBusinessPartner [8] property LinkedBusinessPartner
	*/
	var $LinkedBusinessPartner;

	/**
	 * DISPID=121
	 * @var int $LastMultiReconciliationNum [3] property LastMultiReconciliationNum
	*/
	var $LastMultiReconciliationNum;

	/**
	 * DISPID=122
	 * @var int|VT_USERDEFINED $Equalization [29] property Equalization
	*/
	var $Equalization;

	/**
	 * DISPID=123
	 * @var int|VT_USERDEFINED $SubjectToWithholdingTax [29] property SubjectToWithholdingTax
	*/
	var $SubjectToWithholdingTax;

	/**
	 * DISPID=124
	 * @var string $CertificateNumber [8] property CertificateNumber
	*/
	var $CertificateNumber;

	/**
	 * DISPID=125
	 * @var string|VT_DATE $ExpirationDate [7] property ExpirationDate
	*/
	var $ExpirationDate;

	/**
	 * DISPID=126
	 * @var string $NationalInsuranceNum [8] property NationalInsuranceNum
	*/
	var $NationalInsuranceNum;

	/**
	 * DISPID=127
	 * @var int|VT_USERDEFINED $AccrualCriteria [29] property AccrualCriteria
	*/
	var $AccrualCriteria;

	/**
	 * DISPID=128
	 * @var string $WTCode [8] property WTCode
	*/
	var $WTCode;

	/**
	 * DISPID=129
	 * @var int|VT_USERDEFINED $DeferredTax [29] property DeferredTax
	*/
	var $DeferredTax;

	/**
	 * DISPID=130
	 * @var string $BillToBuildingFloorRoom [8] property BillToBuildingFloorRoom
	*/
	var $BillToBuildingFloorRoom;

	/**
	 * DISPID=131
	 * @var string $DownPaymentClearAct [8] property DownPaymentClearAct
	*/
	var $DownPaymentClearAct;

	/**
	 * DISPID=132
	 * @var string $ChannelBP [8] property ChannelBP
	*/
	var $ChannelBP;

	/**
	 * DISPID=133
	 * @var int $DefaultTechnician [3] property DefaultTechnician
	*/
	var $DefaultTechnician;

	/**
	 * DISPID=134
	 * @var string $BilltoDefault [8] property BilltoDefault
	*/
	var $BilltoDefault;

	/**
	 * DISPID=135
	 * @var string $CustomerBillofExchangDisc [8] property CustomerBillofExchangDisc
	*/
	var $CustomerBillofExchangDisc;

	/**
	 * DISPID=136
	 * @var int $Territory [3] property Territory
	*/
	var $Territory;

	/**
	 * DISPID=137
	 * @var string $ShipToBuildingFloorRoom [8] property ShipToBuildingFloorRoom
	*/
	var $ShipToBuildingFloorRoom;

	/**
	 * DISPID=138
	 * @var string $CustomerBillofExchangPres [8] property CustomerBillofExchangPres
	*/
	var $CustomerBillofExchangPres;

	/**
	 * DISPID=139
	 * @var mixed|VT_PTR $BPPaymentMethods [26] property BPPaymentMethods
	*/
	var $BPPaymentMethods;

	/**
	 * DISPID=140
	 * @var mixed|VT_PTR $BPWithholdingTax [26] property BPWithholdingTax
	*/
	var $BPWithholdingTax;

	/**
	 * DISPID=141
	 * @var mixed|VT_PTR $BPPaymentDates [26] property BPPaymentDates
	*/
	var $BPPaymentDates;

	/**
	 * DISPID=142
	 * @var mixed|VT_PTR $BPBankAccounts [26] property BPBankAccounts
	*/
	var $BPBankAccounts;

	/**
	 * DISPID=143
	 * @var string $ProjectCode [8] property ProjectCode
	*/
	var $ProjectCode;

	/**
	 * DISPID=144
	 * @var string $VatGroupLatinAmerica [8] property VatGroupLatinAmerica
	*/
	var $VatGroupLatinAmerica;

	/**
	 * DISPID=145
	 * @return string 
	 * Get the object's data in xml format.
	 */
	function GetAsXML()
	{
	}

	/**
	 * DISPID=146
	 * @param string $FileName [in]
	 * @return void 
	 * Save the object's data in xml format.
	 */
	function SaveToFile(
		/* string [8] [in] */ $FileName 
	)
	{
	}

	/**
	 * DISPID=147
	 * @var string $DunningTerm [8] property DunningTerm
	*/
	var $DunningTerm;

	/**
	 * DISPID=148
	 * @var string $Website [8] property Website
	*/
	var $Website;

	/**
	 * DISPID=149
	 * @var string $OtherReceivablePayable [8] property OtherReceivablePayable
	*/
	var $OtherReceivablePayable;

	/**
	 * DISPID=150
	 * @var int $ClosingDateProcedureNumber [3] property ClosingDateProcedureNumber
	*/
	var $ClosingDateProcedureNumber;

	/**
	 * DISPID=151
	 * @var string $Profession [8] property Profession
	*/
	var $Profession;

	/**
	 * DISPID=152
	 * @var string $BillofExchangeonCollection [8] property BillofExchangeonCollection
	*/
	var $BillofExchangeonCollection;

	/**
	 * DISPID=153
	 * @var int|VT_USERDEFINED $CompanyPrivate [29] property CompanyPrivate
	*/
	var $CompanyPrivate;

	/**
	 * DISPID=154
	 * @var int $LanguageCode [3] property LanguageCode
	*/
	var $LanguageCode;

	/**
	 * DISPID=155
	 * @var string $UnpaidBillofExchange [8] property UnpaidBillofExchange
	*/
	var $UnpaidBillofExchange;

	/**
	 * DISPID=156
	 * @var int $WithholdingTaxDeductionGroup [3] property WithholdingTaxDeductionGroup
	*/
	var $WithholdingTaxDeductionGroup;

	/**
	 * DISPID=157
	 * @var string $BankChargesAllocationCode [8] property BankChargesAllocationCode
	*/
	var $BankChargesAllocationCode;

	/**
	 * DISPID=158
	 * @var IBPFiscalTaxID $FiscalTaxID [26] property FiscalTaxID
	*/
	var $FiscalTaxID;

	/**
	 * DISPID=159
	 * @var int|VT_USERDEFINED $TaxRoundingRule [29] property TaxRoundingRule
	*/
	var $TaxRoundingRule;

	/**
	 * DISPID=160
	 * @var string $CompanyRegistrationNumber [8] property CompanyRegistrationNumber
	*/
	var $CompanyRegistrationNumber;

	/**
	 * DISPID=161
	 * @var string $VerificationNumber [8] property VerificationNumber
	*/
	var $VerificationNumber;

	/**
	 * DISPID=162
	 * @var int|VT_USERDEFINED $OperationCode347 [29] property OperationCode347
	*/
	var $OperationCode347;

	/**
	 * DISPID=163
	 * @var int|VT_USERDEFINED $InsuranceOperation347 [29] property InsuranceOperation347
	*/
	var $InsuranceOperation347;

	/**
	 * DISPID=164
	 * @var int|VT_USERDEFINED $DiscountBaseObject [29] property DiscountBaseObject
	*/
	var $DiscountBaseObject;

	/**
	 * DISPID=165
	 * @var int|VT_USERDEFINED $DiscountRelations [29] property DiscountRelations
	*/
	var $DiscountRelations;

	/**
	 * DISPID=166
	 * @var mixed|VT_PTR $DiscountGroups [26] property DiscountGroups
	*/
	var $DiscountGroups;

	/**
	 * DISPID=167
	 * @var int|VT_USERDEFINED $TypeReport [29] property TypeReport
	*/
	var $TypeReport;

	/**
	 * DISPID=168
	 * @var int|VT_USERDEFINED $ThresholdOverlook [29] property ThresholdOverlook
	*/
	var $ThresholdOverlook;

	/**
	 * DISPID=169
	 * @var int|VT_USERDEFINED $SurchargeOverlook [29] property SurchargeOverlook
	*/
	var $SurchargeOverlook;

	/**
	 * DISPID=170
	 * @var string $DownPaymentInterimAccount [8] property DownPaymentInterimAccount
	*/
	var $DownPaymentInterimAccount;

	/**
	 * DISPID=171
	 * @var int|VT_USERDEFINED $HierarchicalDeduction [29] property HierarchicalDeduction
	*/
	var $HierarchicalDeduction;

	/**
	 * DISPID=172
	 * @var int|VT_USERDEFINED $ShaamGroup [29] property ShaamGroup
	*/
	var $ShaamGroup;

	/**
	 * DISPID=173
	 * @var int|VT_USERDEFINED $WithholdingTaxCertified [29] property WithholdingTaxCertified
	*/
	var $WithholdingTaxCertified;

	/**
	 * DISPID=174
	 * @var int|VT_USERDEFINED $BookkeepingCertified [29] property BookkeepingCertified
	*/
	var $BookkeepingCertified;

	/**
	 * DISPID=175
	 * @var string $PlanningGroup [8] property PlanningGroup
	*/
	var $PlanningGroup;

	/**
	 * DISPID=176
	 * @var int|VT_USERDEFINED $Affiliate [29] property Affiliate
	*/
	var $Affiliate;

	/**
	 * DISPID=177
	 * @var int $Industry [3] property Industry
	*/
	var $Industry;

	/**
	 * DISPID=178
	 * @var string $VatIDNum [8] property VatIDNum
	*/
	var $VatIDNum;

	/**
	 * DISPID=179
	 * @var int $DatevAccount [3] property DatevAccount
	*/
	var $DatevAccount;

	/**
	 * DISPID=180
	 * @var int|VT_USERDEFINED $DatevFirstDataEntry [29] property DatevFirstDataEntry
	*/
	var $DatevFirstDataEntry;

	/**
	 * DISPID=181
	 * @var string $GTSRegNo [8] property GTSRegNo
	*/
	var $GTSRegNo;

	/**
	 * DISPID=182
	 * @var string $GTSBankAccountNo [8] property GTSBankAccountNo
	*/
	var $GTSBankAccountNo;

	/**
	 * DISPID=183
	 * @var string $GTSBillingAddrTel [8] property GTSBillingAddrTel
	*/
	var $GTSBillingAddrTel;

	/**
	 * DISPID=184
	 * @var int $ETaxWebSite [3] property ETaxWebSite
	*/
	var $ETaxWebSite;

	/**
	 * DISPID=185
	 * @var string $HouseBankIBAN [8] property HouseBankIBAN
	*/
	var $HouseBankIBAN;

	/**
	 * DISPID=186
	 * @var int $Series [3] property Series
	*/
	var $Series;

	/**
	 * DISPID=187
	 * @var int|VT_USERDEFINED $AutomaticPosting [29] property AutomaticPosting
	*/
	var $AutomaticPosting;

	/**
	 * DISPID=188
	 * @var string $InterestAccount [8] property InterestAccount
	*/
	var $InterestAccount;

	/**
	 * DISPID=189
	 * @var string $FeeAccount [8] property FeeAccount
	*/
	var $FeeAccount;

	/**
	 * DISPID=190
	 * @var int $CampaignNumber [3] property CampaignNumber
	*/
	var $CampaignNumber;

	/**
	 * DISPID=191
	 * @param string $FileName [in]
	 * @return int 
	 * method UpdateFromXML
	 */
	function UpdateFromXML(
		/* string [8] [in] */ $FileName 
	)
	{
	}

	/**
	 * DISPID=192
	 * @var string $VATRegistrationNumber [8] property VATRegistrationNumber
	*/
	var $VATRegistrationNumber;

	/**
	 * DISPID=193
	 * @var string $RepresentativeName [8] property RepresentativeName
	*/
	var $RepresentativeName;

	/**
	 * DISPID=194
	 * @var string $IndustryType [8] property IndustryType
	*/
	var $IndustryType;

	/**
	 * DISPID=195
	 * @var string $BusinessType [8] property BusinessType
	*/
	var $BusinessType;

	/**
	 * DISPID=201
	 * @var mixed|VT_PTR $BPBranchAssignment [26] property BPBranchAssignment
	*/
	var $BPBranchAssignment;

	/**
	 * DISPID=202
	 * @var string $AliasName [8] property AliasName
	*/
	var $AliasName;

	/**
	 * DISPID=203
	 * @var int $DefaultBlanketAgreementNumber [3] property DefaultBlanketAgreementNumber
	*/
	var $DefaultBlanketAgreementNumber;

	/**
	 * DISPID=204
	 * @var int|VT_USERDEFINED $EffectiveDiscount [29] property EffectiveDiscount
	*/
	var $EffectiveDiscount;

	/**
	 * DISPID=205
	 * @var int|VT_USERDEFINED $NoDiscounts [29] property NoDiscounts
	*/
	var $NoDiscounts;

	/**
	 * DISPID=206
	 * @var string $GlobalLocationNumber [8] property GlobalLocationNumber
	*/
	var $GlobalLocationNumber;

	/**
	 * DISPID=207
	 * @var string $EDISenderID [8] property EDISenderID
	*/
	var $EDISenderID;

	/**
	 * DISPID=208
	 * @var string $EDIRecipientID [8] property EDIRecipientID
	*/
	var $EDIRecipientID;

	/**
	 * DISPID=209
	 * @var int|VT_USERDEFINED $ResidenNumber [29] property ResidenNumber
	*/
	var $ResidenNumber;

	/**
	 * DISPID=210
	 * @var mixed|VT_PTR $IntrastatExtension [26] property IntrastatExtension
	*/
	var $IntrastatExtension;

	/**
	 * DISPID=211
	 * @var string $UnifiedFederalTaxID [8] property UnifiedFederalTaxID
	*/
	var $UnifiedFederalTaxID;

	/**
	 * DISPID=212
	 * @var string|VT_DATE $RelationshipDateFrom [7] property RelationshipDateFrom
	*/
	var $RelationshipDateFrom;

	/**
	 * DISPID=213
	 * @var string|VT_DATE $RelationshipDateTill [7] property RelationshipDateTill
	*/
	var $RelationshipDateTill;

	/**
	 * DISPID=214
	 * @var string $RelationshipCode [8] property RelationshipCode
	*/
	var $RelationshipCode;

	/**
	 * DISPID=215
	 * @var int $AttachmentEntry [3] property AttachmentEntry
	*/
	var $AttachmentEntry;

	/**
	 * DISPID=216
	 * @var int|VT_USERDEFINED $TypeOfOperation [29] property TypeOfOperation
	*/
	var $TypeOfOperation;

	/**
	 * DISPID=217
	 * @var int $OwnerCode [3] property OwnerCode
	*/
	var $OwnerCode;

	/**
	 * DISPID=218
	 * @var int|VT_USERDEFINED $EndorsableChecksFromBP [29] property EndorsableChecksFromBP
	*/
	var $EndorsableChecksFromBP;

	/**
	 * DISPID=219
	 * @var int|VT_USERDEFINED $AcceptsEndorsedChecks [29] property AcceptsEndorsedChecks
	*/
	var $AcceptsEndorsedChecks;

	/**
	 * DISPID=220
	 * @var int|VT_USERDEFINED $BlockSendingMarketingContent [29] property BlockSendingMarketingContent
	*/
	var $BlockSendingMarketingContent;

	/**
	 * DISPID=221
	 * @var mixed|VT_PTR $BPBlockSendingMarketingContents [26] property BPBlockSendingMarketingContents
	*/
	var $BPBlockSendingMarketingContents;

	/**
	 * DISPID=222
	 * @var string $AgentCode [8] property AgentCode
	*/
	var $AgentCode;

}