<?php
/**
 * Created by PhpStorm.
 * User: E-Commerce 2
 * Date: 28/11/2016
 * Time: 18:14
 */

namespace Litiano\Sap\IdeHelper;



class IBusinessPartners { /* GUID={9DF321C2-6A1D-446B-AE8A-F7C33987D792} */
    /* DISPID=1610612736 */
    function QueryInterface(
        /* VT_PTR [26] [in] --> ? [29]  */ &$riid,
        /* VT_PTR [26] [out] --> VT_PTR [26]  */ &$ppvObj
    )
    {
    }
    /* DISPID=1610612737 */
    /* VT_UI4 [19] */
    function AddRef(
    )
    {
    }
    /* DISPID=1610612738 */
    /* VT_UI4 [19] */
    function Release(
    )
    {
    }
    /* DISPID=1610678272 */
    function GetTypeInfoCount(
        /* VT_PTR [26] [out] --> VT_UINT [23]  */ &$pctinfo
    )
    {
    }
    /* DISPID=1610678273 */
    function GetTypeInfo(
        /* VT_UINT [23] [in] */ $itinfo,
        /* VT_UI4 [19] [in] */ $lcid,
        /* VT_PTR [26] [out] --> VT_PTR [26]  */ &$pptinfo
    )
    {
    }
    /* DISPID=1610678274 */
    function GetIDsOfNames(
        /* VT_PTR [26] [in] --> ? [29]  */ &$riid,
        /* VT_PTR [26] [in] --> VT_PTR [26]  */ &$rgszNames,
        /* VT_UINT [23] [in] */ $cNames,
        /* VT_UI4 [19] [in] */ $lcid,
        /* VT_PTR [26] [out] --> VT_I4 [3]  */ &$rgdispid
    )
    {
    }
    /* DISPID=1610678275 */
    function Invoke(
        /* VT_I4 [3] [in] */ $dispidMember,
        /* VT_PTR [26] [in] --> ? [29]  */ &$riid,
        /* VT_UI4 [19] [in] */ $lcid,
        /* VT_UI2 [18] [in] */ $wFlags,
        /* VT_PTR [26] [in] --> ? [29]  */ &$pdispparams,
        /* VT_PTR [26] [out] --> VT_VARIANT [12]  */ &$pvarResult,
        /* VT_PTR [26] [out] --> ? [29]  */ &$pexcepinfo,
        /* VT_PTR [26] [out] --> VT_UINT [23]  */ &$puArgErr
    )
    {
    }
    /* DISPID=1 */
    /* VT_BSTR [8] */
    /* In this field, type in the code you have chosen for the customer or supplier: a fifteen-character, alphanumeric code */
    var $CardCode;

    /* DISPID=1 */
    /* In this field, type in the code you have chosen for the customer or supplier: a fifteen-character, alphanumeric code */
    var $CardCode;

    /* DISPID=3 */
    /* ? [29] */
    /* From the field's drop down menu you must determine whether  the card is for a customer or supplier. If a business is both a customer and supplier, define two cards. */
    var $CardType;

    /* DISPID=3 */
    /* From the field's drop down menu you must determine whether  the card is for a customer or supplier. If a business is both a customer and supplier, define two cards. */
    var $CardType;

    /* DISPID=4 */
    /* VT_BSTR [8] */
    /* You must enter the full customer/supplier name in this field. */
    var $CardName;

    /* DISPID=4 */
    /* You must enter the full customer/supplier name in this field. */
    var $CardName;

    /* DISPID=5 */
    /* VT_I4 [3] */
    /* In this field, select the association group for the customer or supplier. You can use this association to generate any report from a specific cross-section of cards. */
    var $GroupCode;

    /* DISPID=5 */
    /* In this field, select the association group for the customer or supplier. You can use this association to generate any report from a specific cross-section of cards. */
    var $GroupCode;

    /* DISPID=7 */
    /* VT_BSTR [8] */
    /* An address should be entered in these fields only if 					  the physical address is not the same as the mailing address.					  If there is no entry for Address in a new card the system will 					  copy the data from Mailing Address to these fields. */

    var $Address;

    /* DISPID=7 */
    /* An address should be entered in these fields only if 					  the physical address is not the same as the mailing address.					  If there is no entry for Address in a new card the system will 					  copy the data from Mailing Address to these fields. */
    var $Address;

    /* DISPID=8 */
    /* VT_BSTR [8] */
    /* Zip Code for Company address. */
    var $ZipCode;

    /* DISPID=8 */
    /* Zip Code for Company address. */
    var $ZipCode;

    /* DISPID=9 */
    /* VT_BSTR [8] */
    /* In the relevant fields, enter the mailing address provided by the customer or supplier. This address appears on marketing and payment documents generated by TM Pro. */
    var $MailAddress;

    /* DISPID=9 */
    /* In the relevant fields, enter the mailing address provided by the customer or supplier. This address appears on marketing and payment documents generated by TM Pro. */
    var $MailAddress;

    /* DISPID=10 */
    /* VT_BSTR [8] */
    /* Zip Code for mailing Address. */
    var $MailZipCode;

    /* DISPID=10 */
    /* Zip Code for mailing Address. */
    var $MailZipCode;

    /* DISPID=11 */
    /* VT_BSTR [8] */
    /* Tel 1 number. */
    var $Phone1;

    /* DISPID=11 */
    /* Tel 1 number. */
    var $Phone1;

    /* DISPID=12 */
    /* VT_BSTR [8] */
    /* Tel 2 number. */
    var $Phone2;

    /* DISPID=12 */
    /* Tel 2 number. */
    var $Phone2;

    /* DISPID=13 */
    /* VT_BSTR [8] */
    /* Fax number. */
    var $Fax;

    /* DISPID=13 */
    /* Fax number. */
    var $Fax;

    /* DISPID=14 */
    /* VT_BSTR [8] */
    /* Contact person name. */
    var $ContactPerson;

    /* DISPID=14 */
    /* Contact person name. */
    var $ContactPerson;

    /* DISPID=15 */
    /* VT_BSTR [8] */
    /* This field allows you to type in any text you want about the customer. For example, “Customer entitled to preferred treatment? or conversely, “No checks? */
    var $Notes;

    /* DISPID=15 */
    /* This field allows you to type in any text you want about the customer. For example, “Customer entitled to preferred treatment? or conversely, “No checks? */
    var $Notes;

    /* DISPID=16 */
    /* VT_I4 [3] */
    /* Payment terms group number. */
    var $PayTermsGrpCode;

    /* DISPID=16 */
    /* Payment terms group number. */
    var $PayTermsGrpCode;

    /* DISPID=17 */
    /* VT_R8 [5] */
    /* Maximal credit. */
    var $CreditLimit;

    /* DISPID=17 */
    /* Maximal credit. */
    var $CreditLimit;

    /* DISPID=18 */
    /* VT_R8 [5] */
    /* Maximal debt. */
    var $MaxCommitment;

    /* DISPID=18 */
    /* Maximal debt. */
    var $MaxCommitment;

    /* DISPID=19 */
    /* VT_R8 [5] */
    /* Overall Discount %. */
    var $DiscountPercent;

    /* DISPID=19 */
    /* Overall Discount %. */
    var $DiscountPercent;

    /* DISPID=20 */
    /* ? [29] */
    /* The default is Yes. If the customer is exempt, you must select the No option. */
    var $VatLiable;

    /* DISPID=20 */
    /* The default is Yes. If the customer is exempt, you must select the No option. */
    var $VatLiable;

    /* DISPID=21 */
    /* VT_BSTR [8] */
    /* Type the customer or supplier L.T. no. in this field. */
    var $FederalTaxID;

    /* DISPID=21 */
    /* Type the customer or supplier L.T. no. in this field. */
    var $FederalTaxID;

    /* DISPID=22 */
    /* ? [29] */
    /* Choosing YES for Customer Card indicates that the customer must deduct tax from payments that he pays you. */
    var $DeductibleAtSource;

    /* DISPID=22 */
    /* Choosing YES for Customer Card indicates that the customer must deduct tax from payments that he pays you. */
    var $DeductibleAtSource;

    /* DISPID=23 */
    /* VT_R8 [5] */
    /* You must enter the percentage given in the certificate provided by the supplier.A percentage deduction at source of 5% must be typed as 5, and not as 0.05. */
    var $DeductionPercent;

    /* DISPID=23 */
    /* You must enter the percentage given in the certificate provided by the supplier.A percentage deduction at source of 5% must be typed as 5, and not as 0.05. */
    var $DeductionPercent;

    /* DISPID=24 */
    /* VT_DATE [7] */
    /* Type in the termination date of the certificate provided by the supplier. */
    var $DeductionValidUntil;

    /* DISPID=24 */
    /* Type in the termination date of the certificate provided by the supplier. */
    var $DeductionValidUntil;

    /* DISPID=25 */
    /* VT_I4 [3] */
    /* Price list number. */
    var $PriceListNum;

    /* DISPID=25 */
    /* Price list number. */
    var $PriceListNum;

    /* DISPID=26 */
    /* VT_R8 [5] */
    /* The field specifies the percentage of interest on a delay in payment.  This field is for information only. */
    var $IntrestRatePercent;

    /* DISPID=26 */
    /* The field specifies the percentage of interest on a delay in payment.  This field is for information only. */
    var $IntrestRatePercent;

    /* DISPID=27 */
    /* VT_R8 [5] */
    /* Overwrites the contents of the Percentage Commission field. */
    var $CommissionPercent;

    /* DISPID=27 */
    /* Overwrites the contents of the Percentage Commission field. */
    var $CommissionPercent;

    /* DISPID=28 */
    /* VT_I4 [3] */
    /* Select the desired commission group Number. */
    var $CommissionGroupCode;

    /* DISPID=28 */
    /* Select the desired commission group Number. */
    var $CommissionGroupCode;

    /* DISPID=29 */
    /* VT_BSTR [8] */
    /* Free text such as remarks or other details about the card. */
    var $FreeText;

    /* DISPID=29 */
    /* Free text such as remarks or other details about the card. */
    var $FreeText;

    /* DISPID=30 */
    /* VT_I4 [3] */
    /* Sales employee code. */
    var $SalesPersonCode;

    /* DISPID=30 */
    /* Sales employee code. */
    var $SalesPersonCode;

    /* DISPID=31 */
    /* VT_BSTR [8] */
    /* The card currency is the currency in which all journal entries and marketing documents for that card are performed. The card’s default currency is the local currency, and it is used for all journal entries. */
    var $Currency;

    /* DISPID=31 */
    /* The card currency is the currency in which all journal entries and marketing documents for that card are performed. The card’s default currency is the local currency, and it is used for all journal entries. */
    var $Currency;

    /* DISPID=32 */
    /* VT_BSTR [8] */
    /* Exchange rate differential account. */
    var $RateDiffAccount;

    /* DISPID=32 */
    /* Exchange rate differential account. */
    var $RateDiffAccount;

    /* DISPID=33 */
    /* VT_BSTR [8] */
    /* Cellular phone number. */
    var $Cellular;

    /* DISPID=33 */
    /* Cellular phone number. */
    var $Cellular;

    /* DISPID=34 */
    /* VT_I4 [3] */
    /* In this field, you can type in the average payments delay in days for a specific customer. Entering a value in this field adjusts the value dates of the customer debts in the Cash Flow report. */
    var $AvarageLate;

    /* DISPID=34 */
    /* In this field, you can type in the average payments delay in days for a specific customer. Entering a value in this field adjusts the value dates of the customer debts in the Cash Flow report. */
    var $AvarageLate;

    /* DISPID=35 */
    /* VT_BSTR [8] */
    /* City name for company address. */
    var $City;

    /* DISPID=35 */
    /* City name for company address. */
    var $City;

    /* DISPID=36 */
    /* VT_BSTR [8] */
    /* County name for company address. */
    var $County;

    /* DISPID=36 */
    /* County name for company address. */
    var $County;

    /* DISPID=37 */
    /* VT_BSTR [8] */
    /* Country name for company address. */
    var $Country;

    /* DISPID=37 */
    /* Country name for company address. */
    var $Country;

    /* DISPID=38 */
    /* VT_BSTR [8] */
    /* City for mailing address. */
    var $MailCity;

    /* DISPID=38 */
    /* City for mailing address. */
    var $MailCity;

    /* DISPID=39 */
    /* VT_BSTR [8] */
    /* County for mailing address. */
    var $MailCounty;

    /* DISPID=39 */
    /* County for mailing address. */
    var $MailCounty;

    /* DISPID=40 */
    /* VT_BSTR [8] */
    /* Country for mailing address. */
    var $MailCountry;

    /* DISPID=40 */
    /* Country for mailing address. */
    var $MailCountry;

    /* DISPID=41 */
    /* VT_BSTR [8] */
    /* Company's main Email address. */
    var $EmailAddress;

    /* DISPID=41 */
    /* Company's main Email address. */
    var $EmailAddress;

    /* DISPID=42 */
    /* VT_BSTR [8] */
    /* Picture file name - do not include the full path , only the file name. */
    var $Picture;

    /* DISPID=42 */
    /* Picture file name - do not include the full path , only the file name. */
    var $Picture;

    /* DISPID=43 */
    /* VT_BSTR [8] */
    /* Default bank account. */
    var $DefaultAccount;

    /* DISPID=43 */
    /* Default bank account. */
    var $DefaultAccount;

    /* DISPID=44 */
    /* VT_BSTR [8] */
    /* Default branch. */
    var $DefaultBranch;

    /* DISPID=44 */
    /* Default branch. */
    var $DefaultBranch;

    /* DISPID=45 */
    /* VT_BSTR [8] */
    /* Default bank code. */
    var $DefaultBankCode;

    /* DISPID=45 */
    /* Default bank code. */
    var $DefaultBankCode;

    /* DISPID=46 */
    /* VT_BSTR [8] */
    /* This field allows you to type in an additional ID no. for the card. */
    var $AdditionalID;

    /* DISPID=46 */
    /* This field allows you to type in an additional ID no. for the card. */
    var $AdditionalID;

    /* DISPID=47 */
    /* VT_BSTR [8] */
    /* Pager number. */
    var $Pager;

    /* DISPID=47 */
    /* Pager number. */
    var $Pager;

    /* DISPID=48 */
    /* VT_BSTR [8] */
    /* Father card. */
    var $FatherCard;

    /* DISPID=48 */
    /* Father card. */
    var $FatherCard;

    /* DISPID=49 */
    /* VT_BSTR [8] */
    /* A foreign name can be entered (up to 100 characters). This name will be entered into foreign documents (for example, in an invoice sent to a customer abroad). */
    var $CardForeignName;

    /* DISPID=49 */
    /* A foreign name can be entered (up to 100 characters). This name will be entered into foreign documents (for example, in an invoice sent to a customer abroad). */
    var $CardForeignName;

    /* DISPID=50 */
    /* VT_I4 [3] */
    function Add(
    )
    {
        /* Use this function to add the card to the system. */
    }
    /* DISPID=51 */
    /* ? [29] */
    /* Father type. */
    var $FatherType;

    /* DISPID=51 */
    /* Father type. */
    var $FatherType;

    /* DISPID=52 */
    /* ? [29] */
    /* You use card characteristics for cross-sections and an additional sort of the customer and supplier cards. */
    var $Properties;

    /* DISPID=52 */
    /* You use card characteristics for cross-sections and an additional sort of the customer and supplier cards. */
    var $Properties;

    /* DISPID=53 */
    /* VT_BSTR [8] */
    /* Enter in this field the name of the authorizing official that appears on the supplier’s deduction certificate. */
    var $DeductionOffice;

    /* DISPID=53 */
    /* Enter in this field the name of the authorizing official that appears on the supplier’s deduction certificate. */
    var $DeductionOffice;

    /* DISPID=54 */
    /* VT_BSTR [8] */
    /* Code for data export */
    var $ExportCode;

    /* DISPID=54 */
    /* Code for data export */
    var $ExportCode;

    /* DISPID=55 */
    /* VT_R8 [5] */
    /* Minimal intrest. */
    var $MinIntrest;

    /* DISPID=55 */
    /* Minimal intrest. */
    var $MinIntrest;

    /* DISPID=57 */
    /* VT_BOOL [11] */
    function GetByKey(
        /* VT_BSTR [8]  */ $CardCode
    )
    {
        /* Get a card object by it's key (string value). */
    }
    /* DISPID=58 */
    /* VT_PTR [26] */
    /* User fields for this object. */
    var $UserFields;

    /* DISPID=59 */
    function SaveXML(
        /* VT_PTR [26] [in][out] --> VT_BSTR [8]  */ &$FileName
    )
    {
        /* Save the objects data in xml format. */
    }
    /* DISPID=60 */
    /* VT_I4 [3] */
    function Update(
    )
    {
        /* method Update */
    }
    /* DISPID=61 */
    /* VT_R8 [5] */
    /* property CurrentAccountBalance */
    var $CurrentAccountBalance;

    /* DISPID=62 */
    /* VT_R8 [5] */
    /* property OpenDeliveryNotesBalance */
    var $OpenDeliveryNotesBalance;

    /* DISPID=63 */
    /* VT_R8 [5] */
    /* property OpenOrdersBalance */
    var $OpenOrdersBalance;

    /* DISPID=64 */
    /* VT_PTR [26] */
    /* property ContactEmployees */
    /** @var IContactEmployees */
    var $ContactEmployees;

    /* DISPID=65 */
    /* VT_BSTR [8] */
    /* property VatGroup */
    var $VatGroup;

    /* DISPID=65 */
    /* property VatGroup */
    var $VatGroup;

    /* DISPID=66 */
    /* VT_I4 [3] */
    /* property ShippingType */
    var $ShippingType;

    /* DISPID=66 */
    /* property ShippingType */
    var $ShippingType;

    /* DISPID=67 */
    /* VT_BSTR [8] */
    /* property Password */
    var $Password;

    /* DISPID=67 */
    /* property Password */
    var $Password;

    /* DISPID=68 */
    /* VT_BSTR [8] */
    /* property Indicator */
    var $Indicator;

    /* DISPID=68 */
    /* property Indicator */
    var $Indicator;

    /* DISPID=69 */
    /* VT_BSTR [8] */
    /* property IBAN */
    var $IBAN;

    /* DISPID=69 */
    /* property IBAN */
    var $IBAN;

    /* DISPID=70 */
    /* VT_I4 [3] */
    /* property CreditCardCode */
    var $CreditCardCode;

    /* DISPID=70 */
    /* property CreditCardCode */
    var $CreditCardCode;

    /* DISPID=71 */
    /* VT_BSTR [8] */
    /* property CreditCardNum */
    var $CreditCardNum;

    /* DISPID=71 */
    /* property CreditCardNum */
    var $CreditCardNum;

    /* DISPID=72 */
    /* VT_DATE [7] */
    /* property CreditCardExpiration */
    var $CreditCardExpiration;

    /* DISPID=72 */
    /* property CreditCardExpiration */
    var $CreditCardExpiration;

    /* DISPID=73 */
    /* VT_BSTR [8] */
    /* property PayaybleAccount */
    var $DebitorAccount;

    /* DISPID=73 */
    /* property PayaybleAccount */
    var $DebitorAccount;

    /* DISPID=74 */
    /* VT_I4 [3] */
    function Remove(
    )
    {
        /* method Remove */
    }
    /* DISPID=75 */
    /* VT_I4 [3] */
    function Cancel(
    )
    {
        /* method Cancel */
    }
    /* DISPID=76 */
    /* VT_I4 [3] */
    function Close(
    )
    {
        /* method Close */
    }
    /* DISPID=77 */
    /* VT_I4 [3] */
    /* property OpenOpportunities */
    var $OpenOpportunities;

    /* DISPID=78 */
    /* ? [29] */
    /* property Valid */
    var $Valid;

    /* DISPID=78 */
    /* property Valid */
    var $Valid;

    /* DISPID=79 */
    /* VT_DATE [7] */
    /* property ValidFrom */
    var $ValidFrom;

    /* DISPID=79 */
    /* property ValidFrom */
    var $ValidFrom;

    /* DISPID=80 */
    /* VT_DATE [7] */
    /* property ValidTo */
    var $ValidTo;

    /* DISPID=80 */
    /* property ValidTo */
    var $ValidTo;

    /* DISPID=81 */
    /* VT_BSTR [8] */
    /* property ValidRemarks */
    var $ValidRemarks;

    /* DISPID=81 */
    /* property ValidRemarks */
    var $ValidRemarks;

    /* DISPID=82 */
    /* ? [29] */
    /* property Frozen */
    var $Frozen;

    /* DISPID=82 */
    /* property Frozen */
    var $Frozen;

    /* DISPID=83 */
    /* VT_DATE [7] */
    /* property FrozenFrom */
    var $FrozenFrom;

    /* DISPID=83 */
    /* property FrozenFrom */
    var $FrozenFrom;

    /* DISPID=84 */
    /* VT_DATE [7] */
    /* property FrozenTo */
    var $FrozenTo;

    /* DISPID=84 */
    /* property FrozenTo */
    var $FrozenTo;

    /* DISPID=85 */
    /* VT_BSTR [8] */
    /* property FrozenRemarks */
    var $FrozenRemarks;

    /* DISPID=85 */
    /* property FrozenRemarks */
    var $FrozenRemarks;

    /* DISPID=86 */
    /* VT_PTR [26] */
    /* User fields for this object. */
    var $Browser;

    /* DISPID=87 */
    /* VT_PTR [26] */
    /* property Addresses */
    /**
     * @var $Address IBPAddresses
     */
    var $Addresses;

    /* DISPID=88 */
    /* VT_BSTR [8] */
    /* property Block */
    var $Block;

    /* DISPID=88 */
    /* property Block */
    var $Block;

    /* DISPID=89 */
    /* VT_BSTR [8] */
    /* property BillToState */
    var $BillToState;

    /* DISPID=89 */
    /* property BillToState */
    var $BillToState;

    /* DISPID=90 */
    /* VT_BSTR [8] */
    /* property ExemptNum */
    var $ExemptNum;

    /* DISPID=90 */
    /* property ExemptNum */
    var $ExemptNum;

    /* DISPID=91 */
    /* VT_I4 [3] */
    /* property Priority */
    var $Priority;

    /* DISPID=91 */
    /* property Priority */
    var $Priority;

    /* DISPID=92 */
    /* VT_I4 [3] */
    /* property FormCode1099 */
    var $FormCode1099;

    /* DISPID=92 */
    /* property FormCode1099 */
    var $FormCode1099;

    /* DISPID=93 */
    /* VT_BSTR [8] */
    /* property Box1099 */
    var $Box1099;

    /* DISPID=93 */
    /* property Box1099 */
    var $Box1099;

    /* DISPID=94 */
    /* VT_BSTR [8] */
    /* property PeymentMethodCode */
    var $PeymentMethodCode;

    /* DISPID=94 */
    /* property PeymentMethodCode */
    var $PeymentMethodCode;

    /* DISPID=95 */
    /* ? [29] */
    /* property BackOrder */
    var $BackOrder;

    /* DISPID=95 */
    /* property BackOrder */
    var $BackOrder;

    /* DISPID=96 */
    /* ? [29] */
    /* property PartialDelivery */
    var $PartialDelivery;

    /* DISPID=96 */
    /* property PartialDelivery */
    var $PartialDelivery;

    /* DISPID=97 */
    /* ? [29] */
    /* property BlockDunning */
    var $BlockDunning;

    /* DISPID=97 */
    /* property BlockDunning */
    var $BlockDunning;

    /* DISPID=98 */
    /* VT_BSTR [8] */
    /* property BankCountry */
    var $BankCountry;

    /* DISPID=98 */
    /* property BankCountry */
    var $BankCountry;

    /* DISPID=99 */
    /* VT_BSTR [8] */
    /* property HouseBank */
    var $HouseBank;

    /* DISPID=100 */
    /* VT_BSTR [8] */
    /* property HouseBankCountry */
    var $HouseBankCountry;

    /* DISPID=101 */
    /* VT_BSTR [8] */
    /* property HouseBankAccount */
    var $HouseBankAccount;

    /* DISPID=102 */
    /* VT_BSTR [8] */
    /* property ShipToDefault */
    var $ShipToDefault;

    /* DISPID=102 */
    /* property ShipToDefault */
    var $ShipToDefault;

    /* DISPID=103 */
    /* VT_I4 [3] */
    /* property DunningLevel */
    var $DunningLevel;

    /* DISPID=104 */
    /* VT_DATE [7] */
    /* property DunningDate */
    var $DunningDate;

    /* DISPID=105 */
    /* ? [29] */
    /* property CollectionAuthorization */
    var $CollectionAuthorization;

    /* DISPID=105 */
    /* property CollectionAuthorization */
    var $CollectionAuthorization;

    /* DISPID=106 */
    /* VT_BSTR [8] */
    /* property DME */
    var $DME;

    /* DISPID=106 */
    /* property DME */
    var $DME;

    /* DISPID=107 */
    /* VT_BSTR [8] */
    /* property InstructionKey */
    var $InstructionKey;

    /* DISPID=107 */
    /* property InstructionKey */
    var $InstructionKey;

    /* DISPID=108 */
    /* ? [29] */
    /* property SinglePayment */
    var $SinglePayment;

    /* DISPID=108 */
    /* property SinglePayment */
    var $SinglePayment;

    /* DISPID=109 */
    /* VT_BSTR [8] */
    /* property ISRBillerID */
    var $ISRBillerID;

    /* DISPID=109 */
    /* property ISRBillerID */
    var $ISRBillerID;

    /* DISPID=110 */
    /* ? [29] */
    /* property PaymentBlock */
    var $PaymentBlock;

    /* DISPID=110 */
    /* property PaymentBlock */
    var $PaymentBlock;

    /* DISPID=111 */
    /* VT_BSTR [8] */
    /* property ReferenceDetails */
    var $ReferenceDetails;

    /* DISPID=111 */
    /* property ReferenceDetails */
    var $ReferenceDetails;

    /* DISPID=112 */
    /* VT_BSTR [8] */
    /* property HouseBankBranch */
    var $HouseBankBranch;

    /* DISPID=113 */
    /* VT_BSTR [8] */
    /* property OwnerIDNumber */
    var $OwnerIDNumber;

    /* DISPID=113 */
    /* property OwnerIDNumber */
    var $OwnerIDNumber;

    /* DISPID=114 */
    /* VT_I4 [3] */
    /* property PaymentBlockDescription */
    var $PaymentBlockDescription;

    /* DISPID=114 */
    /* property PaymentBlockDescription */
    var $PaymentBlockDescription;

    /* DISPID=115 */
    /* VT_BSTR [8] */
    /* property TaxExemptionLetterNum */
    var $TaxExemptionLetterNum;

    /* DISPID=116 */
    /* VT_R8 [5] */
    /* property MaxAmountOfExemption */
    var $MaxAmountOfExemption;

    /* DISPID=116 */
    /* property MaxAmountOfExemption */
    var $MaxAmountOfExemption;

    /* DISPID=117 */
    /* VT_DATE [7] */
    /* property ExemptionValidityDateFrom */
    var $ExemptionValidityDateFrom;

    /* DISPID=118 */
    /* VT_DATE [7] */
    /* property ExemptionValidityDateTo */
    var $ExemptionValidityDateTo;

    /* DISPID=119 */
    /* VT_PTR [26] */
    /* property AccountRecivablePayables */
    var $AccountRecivablePayables;

    /* DISPID=120 */
    /* VT_BSTR [8] */
    /* property LinkedBusinessPartner */
    var $LinkedBusinessPartner;

    /* DISPID=120 */
    /* property LinkedBusinessPartner */
    var $LinkedBusinessPartner;

    /* DISPID=121 */
    /* VT_I4 [3] */
    /* property LastMultiReconciliationNum */
    var $LastMultiReconciliationNum;

    /* DISPID=121 */
    /* property LastMultiReconciliationNum */
    var $LastMultiReconciliationNum;

    /* DISPID=122 */
    /* ? [29] */
    /* property Equalization */
    var $Equalization;

    /* DISPID=122 */
    /* property Equalization */
    var $Equalization;

    /* DISPID=123 */
    /* ? [29] */
    /* property SubjectToWithholdingTax */
    var $SubjectToWithholdingTax;

    /* DISPID=123 */
    /* property SubjectToWithholdingTax */
    var $SubjectToWithholdingTax;

    /* DISPID=124 */
    /* VT_BSTR [8] */
    /* property CertificateNumber */
    var $CertificateNumber;

    /* DISPID=124 */
    /* property CertificateNumber */
    var $CertificateNumber;

    /* DISPID=125 */
    /* VT_DATE [7] */
    /* property ExpirationDate */
    var $ExpirationDate;

    /* DISPID=125 */
    /* property ExpirationDate */
    var $ExpirationDate;

    /* DISPID=126 */
    /* VT_BSTR [8] */
    /* property NationalInsuranceNum */
    var $NationalInsuranceNum;

    /* DISPID=126 */
    /* property NationalInsuranceNum */
    var $NationalInsuranceNum;

    /* DISPID=127 */
    /* ? [29] */
    /* property AccrualCriteria */
    var $AccrualCriteria;

    /* DISPID=127 */
    /* property AccrualCriteria */
    var $AccrualCriteria;

    /* DISPID=128 */
    /* VT_BSTR [8] */
    /* property WTCode */
    var $WTCode;

    /* DISPID=128 */
    /* property WTCode */
    var $WTCode;

    /* DISPID=129 */
    /* ? [29] */
    /* property DeferredTax */
    var $DeferredTax;

    /* DISPID=129 */
    /* property DeferredTax */
    var $DeferredTax;

    /* DISPID=130 */
    /* VT_BSTR [8] */
    /* property BillToBuildingFloorRoom */
    var $BillToBuildingFloorRoom;

    /* DISPID=130 */
    /* property BillToBuildingFloorRoom */
    var $BillToBuildingFloorRoom;

    /* DISPID=131 */
    /* VT_BSTR [8] */
    /* property DownPaymentClearAct */
    var $DownPaymentClearAct;

    /* DISPID=131 */
    /* property DownPaymentClearAct */
    var $DownPaymentClearAct;

    /* DISPID=132 */
    /* VT_BSTR [8] */
    /* property ChannelBP */
    var $ChannelBP;

    /* DISPID=132 */
    /* property ChannelBP */
    var $ChannelBP;

    /* DISPID=133 */
    /* VT_I4 [3] */
    /* property DefaultTechnician */
    var $DefaultTechnician;

    /* DISPID=133 */
    /* property DefaultTechnician */
    var $DefaultTechnician;

    /* DISPID=134 */
    /* VT_BSTR [8] */
    /* property BilltoDefault */
    var $BilltoDefault;

    /* DISPID=134 */
    /* property BilltoDefault */
    var $BilltoDefault;

    /* DISPID=135 */
    /* VT_BSTR [8] */
    /* property CustomerBillofExchangDisc */
    var $CustomerBillofExchangDisc;

    /* DISPID=135 */
    /* property CustomerBillofExchangDisc */
    var $CustomerBillofExchangDisc;

    /* DISPID=136 */
    /* VT_I4 [3] */
    /* property Territory */
    var $Territory;

    /* DISPID=136 */
    /* property Territory */
    var $Territory;

    /* DISPID=137 */
    /* VT_BSTR [8] */
    /* property ShipToBuildingFloorRoom */
    var $ShipToBuildingFloorRoom;

    /* DISPID=137 */
    /* property ShipToBuildingFloorRoom */
    var $ShipToBuildingFloorRoom;

    /* DISPID=138 */
    /* VT_BSTR [8] */
    /* property CustomerBillofExchangPres */
    var $CustomerBillofExchangPres;

    /* DISPID=138 */
    /* property CustomerBillofExchangPres */
    var $CustomerBillofExchangPres;

    /* DISPID=139 */
    /* VT_PTR [26] */
    /* property BPPaymentMethods */
    var $BPPaymentMethods;

    /* DISPID=140 */
    /* VT_PTR [26] */
    /* property BPWithholdingTax */
    var $BPWithholdingTax;

    /* DISPID=141 */
    /* VT_PTR [26] */
    /* property BPPaymentDates */
    var $BPPaymentDates;

    /* DISPID=142 */
    /* VT_PTR [26] */
    /* property BPBankAccounts */
    var $BPBankAccounts;

    /* DISPID=143 */
    /* VT_BSTR [8] */
    /* property ProjectCode */
    var $ProjectCode;

    /* DISPID=143 */
    /* property ProjectCode */
    var $ProjectCode;

    /* DISPID=144 */
    /* VT_BSTR [8] */
    /* property VatGroupLatinAmerica */
    var $VatGroupLatinAmerica;

    /* DISPID=144 */
    /* property VatGroupLatinAmerica */
    var $VatGroupLatinAmerica;

    /* DISPID=145 */
    /* VT_BSTR [8] */
    function GetAsXML(
    )
    {
        /* Get the object's data in xml format. */
    }
    /* DISPID=146 */
    function SaveToFile(
        /* VT_BSTR [8] [in] */ $FileName
    )
    {
        /* Save the object's data in xml format. */
    }
    /* DISPID=147 */
    /* VT_BSTR [8] */
    /* property DunningTerm */
    var $DunningTerm;

    /* DISPID=147 */
    /* property DunningTerm */
    var $DunningTerm;

    /* DISPID=99 */
    /* property HouseBank */
    var $HouseBank;

    /* DISPID=100 */
    /* property HouseBankCountry */
    var $HouseBankCountry;

    /* DISPID=101 */
    /* property HouseBankAccount */
    var $HouseBankAccount;

    /* DISPID=112 */
    /* property HouseBankBranch */
    var $HouseBankBranch;

    /* DISPID=148 */
    /* VT_BSTR [8] */
    /* property Website */
    var $Website;

    /* DISPID=148 */
    /* property Website */
    var $Website;

    /* DISPID=149 */
    /* VT_BSTR [8] */
    /* property OtherReceivablePayable */
    var $OtherReceivablePayable;

    /* DISPID=150 */
    /* VT_I4 [3] */
    /* property ClosingDateProcedureNumber */
    var $ClosingDateProcedureNumber;

    /* DISPID=150 */
    /* property ClosingDateProcedureNumber */
    var $ClosingDateProcedureNumber;

    /* DISPID=151 */
    /* VT_BSTR [8] */
    /* property Profession */
    var $Profession;

    /* DISPID=151 */
    /* property Profession */
    var $Profession;

    /* DISPID=152 */
    /* VT_BSTR [8] */
    /* property BillofExchangeonCollection */
    var $BillofExchangeonCollection;

    /* DISPID=152 */
    /* property BillofExchangeonCollection */
    var $BillofExchangeonCollection;

    /* DISPID=153 */
    /* ? [29] */
    /* property CompanyPrivate */
    var $CompanyPrivate;

    /* DISPID=153 */
    /* property CompanyPrivate */
    var $CompanyPrivate;

    /* DISPID=154 */
    /* VT_I4 [3] */
    /* property LanguageCode */
    var $LanguageCode;

    /* DISPID=154 */
    /* property LanguageCode */
    var $LanguageCode;

    /* DISPID=155 */
    /* VT_BSTR [8] */
    /* property UnpaidBillofExchange */
    var $UnpaidBillofExchange;

    /* DISPID=155 */
    /* property UnpaidBillofExchange */
    var $UnpaidBillofExchange;

    /* DISPID=156 */
    /* VT_I4 [3] */
    /* property WithholdingTaxDeductionGroup */
    var $WithholdingTaxDeductionGroup;

    /* DISPID=156 */
    /* property WithholdingTaxDeductionGroup */
    var $WithholdingTaxDeductionGroup;

    /* DISPID=157 */
    /* VT_BSTR [8] */
    /* property BankChargesAllocationCode */
    var $BankChargesAllocationCode;

    /* DISPID=157 */
    /* property BankChargesAllocationCode */
    var $BankChargesAllocationCode;

    /* DISPID=158 */
    /* VT_PTR [26] */
    /* property FiscalTaxID */
    /**
     * @var $FiscalTaxID IBPFiscalTaxID
     */
    var $FiscalTaxID;

    /* DISPID=159 */
    /* ? [29] */
    /* property TaxRoundingRule */
    var $TaxRoundingRule;

    /* DISPID=159 */
    /* property TaxRoundingRule */
    var $TaxRoundingRule;

    /* DISPID=115 */
    /* property TaxExemptionLetterNum */
    var $TaxExemptionLetterNum;

    /* DISPID=117 */
    /* property ExemptionValidityDateFrom */
    var $ExemptionValidityDateFrom;

    /* DISPID=118 */
    /* property ExemptionValidityDateTo */
    var $ExemptionValidityDateTo;

    /* DISPID=160 */
    /* VT_BSTR [8] */
    /* property CompanyRegistrationNumber */
    var $CompanyRegistrationNumber;

    /* DISPID=160 */
    /* property CompanyRegistrationNumber */
    var $CompanyRegistrationNumber;

    /* DISPID=161 */
    /* VT_BSTR [8] */
    /* property VerificationNumber */
    var $VerificationNumber;

    /* DISPID=161 */
    /* property VerificationNumber */
    var $VerificationNumber;

    /* DISPID=149 */
    /* property OtherReceivablePayable */
    var $OtherReceivablePayable;

    /* DISPID=162 */
    /* ? [29] */
    /* property OperationCode347 */
    var $OperationCode347;

    /* DISPID=162 */
    /* property OperationCode347 */
    var $OperationCode347;

    /* DISPID=163 */
    /* ? [29] */
    /* property InsuranceOperation347 */
    var $InsuranceOperation347;

    /* DISPID=163 */
    /* property InsuranceOperation347 */
    var $InsuranceOperation347;

    /* DISPID=164 */
    /* ? [29] */
    /* property DiscountBaseObject */
    var $DiscountBaseObject;

    /* DISPID=164 */
    /* property DiscountBaseObject */
    var $DiscountBaseObject;

    /* DISPID=165 */
    /* ? [29] */
    /* property DiscountRelations */
    var $DiscountRelations;

    /* DISPID=165 */
    /* property DiscountRelations */
    var $DiscountRelations;

    /* DISPID=166 */
    /* VT_PTR [26] */
    /* property DiscountGroups */
    var $DiscountGroups;

    /* DISPID=167 */
    /* ? [29] */
    /* property TypeReport */
    var $TypeReport;

    /* DISPID=167 */
    /* property TypeReport */
    var $TypeReport;

    /* DISPID=168 */
    /* ? [29] */
    /* property ThresholdOverlook */
    var $ThresholdOverlook;

    /* DISPID=168 */
    /* property ThresholdOverlook */
    var $ThresholdOverlook;

    /* DISPID=169 */
    /* ? [29] */
    /* property SurchargeOverlook */
    var $SurchargeOverlook;

    /* DISPID=169 */
    /* property SurchargeOverlook */
    var $SurchargeOverlook;

    /* DISPID=170 */
    /* VT_BSTR [8] */
    /* property DownPaymentInterimAccount */
    var $DownPaymentInterimAccount;

    /* DISPID=170 */
    /* property DownPaymentInterimAccount */
    var $DownPaymentInterimAccount;

    /* DISPID=171 */
    /* ? [29] */
    /* property HierarchicalDeduction */
    var $HierarchicalDeduction;

    /* DISPID=171 */
    /* property HierarchicalDeduction */
    var $HierarchicalDeduction;

    /* DISPID=172 */
    /* ? [29] */
    /* property ShaamGroup */
    var $ShaamGroup;

    /* DISPID=172 */
    /* property ShaamGroup */
    var $ShaamGroup;

    /* DISPID=173 */
    /* ? [29] */
    /* property WithholdingTaxCertified */
    var $WithholdingTaxCertified;

    /* DISPID=173 */
    /* property WithholdingTaxCertified */
    var $WithholdingTaxCertified;

    /* DISPID=174 */
    /* ? [29] */
    /* property BookkeepingCertified */
    var $BookkeepingCertified;

    /* DISPID=174 */
    /* property BookkeepingCertified */
    var $BookkeepingCertified;

    /* DISPID=175 */
    /* VT_BSTR [8] */
    /* property PlanningGroup */
    var $PlanningGroup;

    /* DISPID=175 */
    /* property PlanningGroup */
    var $PlanningGroup;

    /* DISPID=176 */
    /* ? [29] */
    /* property Affiliate */
    var $Affiliate;

    /* DISPID=176 */
    /* property Affiliate */
    var $Affiliate;

    /* DISPID=177 */
    /* VT_I4 [3] */
    /* property Industry */
    var $Industry;

    /* DISPID=177 */
    /* property Industry */
    var $Industry;

    /* DISPID=178 */
    /* VT_BSTR [8] */
    /* property VatIDNum */
    var $VatIDNum;

    /* DISPID=178 */
    /* property VatIDNum */
    var $VatIDNum;

    /* DISPID=179 */
    /* VT_I4 [3] */
    /* property DatevAccount */
    var $DatevAccount;

    /* DISPID=179 */
    /* property DatevAccount */
    var $DatevAccount;

    /* DISPID=180 */
    /* ? [29] */
    /* property DatevFirstDataEntry */
    var $DatevFirstDataEntry;

    /* DISPID=180 */
    /* property DatevFirstDataEntry */
    var $DatevFirstDataEntry;

    /* DISPID=181 */
    /* VT_BSTR [8] */
    /* property GTSRegNo */
    var $GTSRegNo;

    /* DISPID=181 */
    /* property GTSRegNo */
    var $GTSRegNo;

    /* DISPID=182 */
    /* VT_BSTR [8] */
    /* property GTSBankAccountNo */
    var $GTSBankAccountNo;

    /* DISPID=182 */
    /* property GTSBankAccountNo */
    var $GTSBankAccountNo;

    /* DISPID=183 */
    /* VT_BSTR [8] */
    /* property GTSBillingAddrTel */
    var $GTSBillingAddrTel;

    /* DISPID=183 */
    /* property GTSBillingAddrTel */
    var $GTSBillingAddrTel;

    /* DISPID=184 */
    /* VT_I4 [3] */
    /* property ETaxWebSite */
    var $ETaxWebSite;

    /* DISPID=184 */
    /* property ETaxWebSite */
    var $ETaxWebSite;

    /* DISPID=185 */
    /* VT_BSTR [8] */
    /* property HouseBankIBAN */
    var $HouseBankIBAN;

    /* DISPID=186 */
    /* VT_I4 [3] */
    /* property Series */
    var $Series;

    /* DISPID=186 */
    /* property Series */
    var $Series;

    /* DISPID=187 */
    /* ? [29] */
    /* property AutomaticPosting */
    var $AutomaticPosting;

    /* DISPID=187 */
    /* property AutomaticPosting */
    var $AutomaticPosting;

    /* DISPID=188 */
    /* VT_BSTR [8] */
    /* property InterestAccount */
    var $InterestAccount;

    /* DISPID=188 */
    /* property InterestAccount */
    var $InterestAccount;

    /* DISPID=189 */
    /* VT_BSTR [8] */
    /* property FeeAccount */
    var $FeeAccount;

    /* DISPID=189 */
    /* property FeeAccount */
    var $FeeAccount;

    /* DISPID=190 */
    /* VT_I4 [3] */
    /* property CampaignNumber */
    var $CampaignNumber;

    /* DISPID=190 */
    /* property CampaignNumber */
    var $CampaignNumber;

    /* DISPID=191 */
    /* VT_I4 [3] */
    function UpdateFromXML(
        /* VT_BSTR [8] [in] */ $FileName
    )
    {
        /* method UpdateFromXML */
    }
    /* DISPID=192 */
    /* VT_BSTR [8] */
    /* property VATRegistrationNumber */
    var $VATRegistrationNumber;

    /* DISPID=192 */
    /* property VATRegistrationNumber */
    var $VATRegistrationNumber;

    /* DISPID=193 */
    /* VT_BSTR [8] */
    /* property RepresentativeName */
    var $RepresentativeName;

    /* DISPID=193 */
    /* property RepresentativeName */
    var $RepresentativeName;

    /* DISPID=194 */
    /* VT_BSTR [8] */
    /* property IndustryType */
    var $IndustryType;

    /* DISPID=194 */
    /* property IndustryType */
    var $IndustryType;

    /* DISPID=195 */
    /* VT_BSTR [8] */
    /* property BusinessType */
    var $BusinessType;

    /* DISPID=195 */
    /* property BusinessType */
    var $BusinessType;

    /* DISPID=201 */
    /* VT_PTR [26] */
    /* property BPBranchAssignment */
    var $BPBranchAssignment;

    /* DISPID=202 */
    /* VT_BSTR [8] */
    /* property AliasName */
    var $AliasName;

    /* DISPID=202 */
    /* property AliasName */
    var $AliasName;

    /* DISPID=203 */
    /* VT_I4 [3] */
    /* property DefaultBlanketAgreementNumber */
    var $DefaultBlanketAgreementNumber;

    /* DISPID=203 */
    /* property DefaultBlanketAgreementNumber */
    var $DefaultBlanketAgreementNumber;

    /* DISPID=204 */
    /* ? [29] */
    /* property EffectiveDiscount */
    var $EffectiveDiscount;

    /* DISPID=204 */
    /* property EffectiveDiscount */
    var $EffectiveDiscount;

    /* DISPID=205 */
    /* ? [29] */
    /* property NoDiscounts */
    var $NoDiscounts;

    /* DISPID=205 */
    /* property NoDiscounts */
    var $NoDiscounts;

    /* DISPID=206 */
    /* VT_BSTR [8] */
    /* property GlobalLocationNumber */
    var $GlobalLocationNumber;

    /* DISPID=206 */
    /* property GlobalLocationNumber */
    var $GlobalLocationNumber;

    /* DISPID=207 */
    /* VT_BSTR [8] */
    /* property EDISenderID */
    var $EDISenderID;

    /* DISPID=207 */
    /* property EDISenderID */
    var $EDISenderID;

    /* DISPID=208 */
    /* VT_BSTR [8] */
    /* property EDIRecipientID */
    var $EDIRecipientID;

    /* DISPID=208 */
    /* property EDIRecipientID */
    var $EDIRecipientID;

    /* DISPID=209 */
    /* ? [29] */
    /* property ResidenNumber */
    var $ResidenNumber;

    /* DISPID=209 */
    /* property ResidenNumber */
    var $ResidenNumber;

}
